openapi: 3.0.3
info:
  title: Calcualdora - Open Api 3.0
  description: 'Interfaz Microservicio de calculadora que realiza operaciones binarias.'
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /api/calculator/operations:
    get:
      tags:
        - calculator-controller
      summary: operaciones binarias
      description: operaciones binarias de suma y resta
      operationId: operation
      parameters:
        - name: number1
          description: Primer operando de la operación
          in: query
          required: true
          schema:
            type: number
          x-example: 3
        - name: number2
          description: Segundo operando de la operación
          in: query
          required: true
          schema:
            type: number
          x-example: 2
        - name: operator
          description: Operación a realizar con los operandos
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/OperatorEnum'
      responses:
        '200':
          description: OK - Resultado de la operación.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ResultResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components: 
  schemas:
    OperatorEnum:
      description: Tipo enumerado para definir la operación a realizar
      type: string
      enum:
        - SUMA
        - RESTA
    ResultResponse:
      description: Resultado de la calculadora con un solo campo
      type: object
      properties:
        result:
          type: number
  
